Uniform argument creation
payjoin/rust-payjoin pull request #117
Opened 2023-11-18 17:34 UTC by arthurmelton

Made to fix https://github.com/payjoin/rust-payjoin/issues/116 and remove the `arg!` macro as a whole.

2023-11-19 17:30 UTC, DanGould requested changes

2023-11-19 17:30 UTC, DanGould commented on payjoin-cli/src/main.rs
> +                    Arg::new("fee-rate")
The arg ID here is inconsistent the above "cookie_file" and "cookie-file". I'd choose the former for ID and latter for argument in the CLI

2023-11-21 00:14 UTC, DanGould commented
@arthurmelton thanks a ton for your first contribution to this repository! I realized my issue wasn't quite as clear as it could be, so I went ahead and changed it based on what I was looking for. I'll merge both commits so that we maintain a record of your help. Thanks for the efforts 😎

(just awaiting msrv fix to merge)

2023-11-21 00:18 UTC, arthurmelton commented
You are all good, I was updating my laptop and was getting in an error hell. I was hoping to get it working soon but currently it's still having its problems. So don't worry about having to update a little bit of it.

2023-11-21 00:24 UTC, merged