Receiver/well known errors
payjoin/rust-payjoin pull request #120
Opened 2023-11-28 17:26 UTC by jbesraa

2023-11-30 19:26 UTC, jbesraa commented
Yea, that makes sense. Will see what they did and try to follow that.

I started actually be reverting the last commit and then started to write test first. 
I am setting up mock server in the integration tests for sender/receiver and testing the response in different scenarios. 
Ill push some commits tomorrow.

2023-12-02 18:26 UTC, DanGould requested changes
Comprehensive looking 😎 Any reason this is review requested but still draft? Because it is, I haven't checked it out yet.

2023-12-05 21:01 UTC, DanGould requested changes
Hate to burst your bubble because I see you've taken a valiant effort to dive into the more difficult error handling territory. But I think there's some confusion between the receiver's bip21 parameters and sender's optional parameters in this last commit.

The version unsupported error is [actually already produced](https://github.com/payjoin/rust-payjoin/blob/745326d67f70a121b0dfb59958032788efa6007b/payjoin/src/receive/error.rs#L98-L105) from `receive`.

This PR should attempt to parse and categorize the response from an independent send module just from the json it receives inside `process_response`

Where Psbt::from_str is called should try to parse the response as a json error if Psbt parsing fails and then return some error, perhaps a `receiver::Error` with ResponseError parsed from receiver json or a ValidationError variants. The ResponseError could contain both known and unknown variants, but only display messages from known errors, as per spec. I believe this was already done in #110 via `WellKnownError::from_str` inside `ResponseError::from_json`.

2023-12-06 11:07 UTC, jbesraa commented
pushed some changes to revert the some of the mistakes introduced yesterday. 
this is still wip and not so ready for review.
i am planning to test the other `KnownError` scenarios and then remove derive from serde

2023-12-06 11:20 UTC, jbesraa commented on payjoin-cli/src/app.rs
> +        let (req, ctx) = payjoin::send::RequestBuilder::from_psbt_and_uri(psbt, uri, version)
motivation > we need a way to provide the sender to specify the version that will be appended in the url

2023-12-13 17:22 UTC, jbesraa commented
@DanGould can you please ACK/NACK the approach i took here

Basically we can parse valid json and valid str-json(please see tests added) without relying on serde.
we only need the `serde_json::Value` as discussed before.

2023-12-13 18:06 UTC, DanGould reviewed
Approach ACK.

That said, It seems to me that `RawResponse` should be completely internal functionality. It seems possible to implement `from_json` on `ResponseError` to parse a *potential* `ResponseError` into `WellKnown`, `Unrecognized` or `Invalid` one on its own like so?

```rs
impl ResponseError {
    fn from_json(json: Value) -> Result<Self, ResponseError> {
        let error_code = json
            .as_object()
            .and_then(|v| v.get("errorCode"))
            .and_then(|v| v.as_str())
            .ok_or(InternalValidationError::Parse)?
            .to_string();
        let message = json
            .as_object()
            .and_then(|v| v.get("message"))
            .and_then(|v| v.as_str())
            .ok_or(InternalValidationError::Parse)?
            .to_string();

        let res_err = match WellKnownError::from_str(&error_code) {
            Ok(e) => ResponseError::WellKnown(e, message),
            Err(_) => ResponseError::Unrecognized(error_code, message),
        };
        Ok(res_err)
    }

    pub fn from_str(response: &str) -> Result<Self, ResponseError> {
        Self::from_json(Value::from_str(response).map_err(|e| {
            log::debug!("Error response must have valid structure, {}", e);
            InternalValidationError::Parse
        })?)
    }
}
```

While typical way to implement `from_str` using serde is by implementing `Deserialize` rather than `from_str` directly, That `deserialize` function would contain your `from_json` behavior and allow `let res_err = serde_json::from_str::<ResponseError>(&res_str)`. It would introduce additional complexity but make it easier to serialize things if they were later e.g. saved to a database in an enterprise environment.

I ACK this approach because it's a good middle ground of simplicity and correctness.

Watch my review process here https://www.loom.com/share/c84cd2f1c2d341e4b1d0bf151b629dcb?sid=1092605e-110f-4b9f-b452-777390433d16

2023-12-14 13:24 UTC, jbesraa commented
Thanks for the input!

TBH I was sure we dont want `serde` at all in the project, but now that I see that u are using it in `V2`, I could indeed just impl `serde::Ser..` and `serde::Des..`.

i agree, we shouldnt expose `RawResponse` but I do think we should keep it and use it internally in `ResponseError`. that way, we can make changes to the internal struct without breaking a pub struct. please see my latest push. 

in general I think all is implemented for the `ResponseError` and its added to `process_response` and that is tested as well.

We have the integration tests and cli that are not using `ResponseError` and using `AnyHow`, should I tackle that in the next commit or we want to do that in a different pr?

2023-12-14 16:36 UTC, DanGould commented
I think we should at least have the errors created here handled in integration tests. It would be nice to have them done properly in the app too

2023-12-14 16:40 UTC, DanGould commented on payjoin/src/send/error.rs
> +                    \"message\":\"This version of payjoin is not supported.\"}";
This is a good opportunity to take advantage of string literals

```suggestion
        let known_str_error = r#"{"errorCode":"version-unsupported", "message":"This version of payjoin is not supported."}"#;

```

2023-12-14 16:41 UTC, DanGould approved these changes

2023-12-14 16:44 UTC, DanGould commented on payjoin/src/send/mod.rs
> +    const ORIGINAL_PROPOSAL: &str = "cHNidP8BAJwCAAAAAo8nutGgJdyYGXWiBEb45Hoe9lWGbkxh/6bNiOJdCDuDAAAAAAD+////jye60aAl3JgZdaIERvjkeh72VYZuTGH/ps2I4l0IO4MBAAAAAP7///8CJpW4BQAAAAAXqRQd6EnwadJ0FQ46/q6Ncu
This should be called `PAYJOIN_PROPOSAL` in BIP 78 parlance

2023-12-18 18:35 UTC, DanGould requested changes
I see that WellKnown now ignores the message. It should still hang on to it for debug, but only return the template for display. So close!

I also now see what you were saying about additional json fields. In spec "version-unsupported" error contains a supported-versions array for example. We're not using it yet, so I don't think it's awful to ignore for the first round, but we must consider that we may support additional json fields in our design (saying we're OK with breaking changes is one way to handle that) in the future as you mentioned over voice 

https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki#optional-parameters

2023-12-18 18:35 UTC, DanGould commented on payjoin/src/send/error.rs
> +        }
Yes, we want wellknown error to only match on `errorCode`, but it should still contain a `message` which may be different than the template. However, only template message will be displayed to the user and the actual message printed to debug log

2023-12-18 18:35 UTC, DanGould commented on payjoin/src/send/error.rs
> +        let known_str_error = r#"{"errorCode":"version-unsupported", "message":"This version of payjoin is not supported."}"#;
This test could make the message distinct from the template, and check that it prints the message to debug and displays the canned "This version of payjoin is not supported"

2023-12-18 18:35 UTC, DanGould commented on payjoin/src/send/error.rs
> +                e.to_string(),
we should print the saved json error message here and use to_string just for display

2023-12-21 19:50 UTC, jbesraa commented
fixed up code to add message and actually separate "message" and "meaning" ugh

2023-12-22 18:22 UTC, DanGould approved these changes
I made a small nit to `WellKnownError` getter return ownership and applied this change to work in the `payjoin-cli` If that floats your boat. I say we merge should you approve my changes on top.

2023-12-22 18:22 UTC, DanGould commented on payjoin/tests/integration.rs
> +            };
I definitely prefer the match asserts to the assert_eq. Seems like that assert_eq could start failing while the response is still spec valid.

2023-12-22 18:22 UTC, DanGould commented on payjoin/tests/integration.rs
> +            );
This seems to be more of a unit test than related to this particular integration since we're mocking the unrecognized error

2023-12-27 20:43 UTC, DanGould commented on payjoin/src/send/error.rs
> +    fn from_error_code(s: &str, message: String) -> Result<Self, ()> {
Seems like this could shortcut directly to an unrecognized error. Just a note in case this gets refactored in the future.

2023-12-27 20:45 UTC, DanGould commented on payjoin/src/send/mod.rs
> +        )
I might check `Eq` between error types instead of the maginc string representation next time

2023-12-27 20:48 UTC, merged

2023-12-27 20:49 UTC, DanGould commented
A nit in the commit log would be that there's a `send` module not `sender` module

2023-12-27 20:50 UTC, DanGould commented
Excellent review volley here. Huge congrats that this is merged 🎉