Handle response status
payjoin/rust-payjoin pull request #284
Opened 2024-06-11 15:16 UTC by DanGould

Oblivious HTTP wraps an HTTP message that contains content and control information. We were ignoring content information like status even though it is essential to the Payjoin V2 protocol. Handle it.

2024-06-17 23:35 UTC, grizznaut requested changes
Tested with "serde" added back into the dependencies list, works fine otherwise.

2024-06-17 23:35 UTC, grizznaut commented on payjoin/src/.DS_Store
Just Mac things

2024-06-17 23:35 UTC, grizznaut commented on payjoin/Cargo.toml
> +v2 = ["bitcoin/rand", "bitcoin/serde", "chacha20poly1305", "dep:http", "dep:bhttp", "dep:ohttp", "url/serde"]
I'm unable to compile with `--features=v2` presumably due to this change?

```
❯ RUST_LOG=debug cargo run --features=v2 -- receive 10000

error[E0433]: failed to resolve: use of undeclared crate or module `serde`
 --> payjoin/src/receive/v2.rs:6:5
  |
6 | use serde::ser::SerializeStruct;
  |     ^^^^^ use of undeclared crate or module `serde`

error[E0432]: unresolved import `serde`
 --> payjoin/src/receive/v2.rs:7:5
  |
7 | use serde::{Deserialize, Serialize, Serializer};
  |     ^^^^^ use of undeclared crate or module `serde`
```

2024-06-18 16:00 UTC, grizznaut reviewed
tACK. It appears the latest `hyper-rustls` breaks MSRV though.

2024-06-18 16:32 UTC, DanGould commented
Yeah, I was a bit sloppy on my last push trying to rebase on master and missed the `serde` dependency.

I'm working on #192 which will include a transition to hyper-1.0 transition to fix msrv without the band-aid that is pinning, but it's going to take a little while. Perhaps I'll get it done today 🤞

2024-06-18 17:48 UTC, DanGould commented
While #192 does need to be addressed, that's actually not related to this exact problem, which is that [reqwest 0.12.5 broke MSRV](https://github.com/seanmonstar/reqwest/issues/2323). I believe my pin is the necessary fix

2024-06-18 18:55 UTC, grizznaut approved these changes

2024-06-18 20:58 UTC, DanGould commented
I removed  had the "pin reqwest" commit since it was merged by #294

2024-06-19 14:24 UTC, merged