WIP - 2S1R example
payjoin/rust-payjoin pull request #434
Opened 2024-12-09 14:40 UTC by 0xBEEFCAF3

Leaving this as a Draft until the TODOs are done. Probably wise to review after its been undrafted. 
For more context please take a look at: https://github.com/orgs/payjoin/discussions/411

TODOs:
* Merge PSBTs code and unit tests
* multiparty typestate machine and unit tests
* sender opt in to optimistic merge
* ns1r int. test

Outside of this PR maybe seperate section describing how multiparty senders would work.

2025-01-15 18:35 UTC, DanGould commented
Can any of this be broken up and merged before all of the TODOs are done? It'd be cool to include this to maintain as an experimental feature as soon as possible and would help inform the shape of a stable API? What does the minimum merge look like?

2025-01-18 00:01 UTC, 0xBEEFCAF3 commented
> Can any of this be broken up and merged before all of the TODOs are done? It'd be cool to include this to maintain as an experimental feature as soon as possible and would help inform the shape of a stable API? What does the minimum merge look like?

Absolutely! Everything multi party related should be featured gated so the risk is minimal. The most minimal change that I would like to make before considering merging are reverting the hacks I had to make to v2 or v1 receiver and sender. This is not a lot of work. After that I will open up for reviews. 

After that the bulk of remaining work is really just validation on both the sender and receiver sides.

2025-01-25 20:16 UTC, DanGould commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
this might be better named AdditionalFeeContribution since it's not the total fee contribution associated with a sender

2025-01-25 21:41 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
I don't think this is valid rust syntax
```rust
type FeeContribution {
  amount: Amount,
  vout: usize,
}
```

Did you mean a struct?

2025-01-25 21:42 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +impl MultiPartyProvisionalProposal {
Done

2025-01-25 21:42 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +    }
Done

2025-01-25 21:49 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
Renamed it for now

2025-01-25 21:49 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +            agg_psbt.combine(proposal).unwrap();
done!

2025-01-25 21:50 UTC, 0xBEEFCAF3 commented
@DanGould moved the psbt merge operation into a submodule of a newly created psbt mod in  [0ff1e4f](https://github.com/payjoin/rust-payjoin/pull/434/commits/0ff1e4f49906f2a5c73e6fa673bac22408b4917e)

The next item is break out multiparty related things in the sender into a multi-party sender submod

2025-01-26 14:19 UTC, DanGould commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
yes struct

2025-01-26 22:54 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
Done

2025-01-28 18:31 UTC, DanGould requested changes
There's a ton here. It's already come a long way.

In order of importance I left comments regarding changes to existing public API, changes to existing modules, the multi-party implementation, my hygiene preferences for innline comments vs docstrings and commit separation.

I think the first commit can be pulled out of this PR and merged. It's unrelated and just nice-to-have. The PSBT merging seems mostly there, and we can merge it early because it should only be enabled in the experimental multi-party feature (which we may want to hide during the experimental phase as `_multi-party`).

I do wonder how much it makes sense for the MergePsbtExt to be a Trait vs. a couple of feature-gated `pub(crate) fn`s. I don't really think it's its own trait, since the trait isn't relied on in a function signature, but rather an extension of functionality, so I lean toward the latter. I think even feature gating the new methods in `PsbtExt` rather than defining a completely new trait would be appropriate since they're internal, but pure functions are simpler.

The multi-party state machine is shaping up. Awesome to see tests work with minimal disruption to the existing abstractions. I'd like to have my comments addressing public API mutations addressed before merge, since afaict they only serve to enable multi-party and make less sense in the context of exclusive `v1`, `v2` use. Same with the changes to existing modules where the abstraction layers get muddy. Let's get those clean before merge.

I'm OK merging the multi-party state machine with some rough edges in the name of progress. We're not going to get it perfect the first time, and it's not going to make complete sense until we have integration into `payjoin-cli`.

I would like to see the inline TODOs that don't define a TODO addressed, straggling lines removed, intermediate commit lint errors addressed, and inline comments pushed into docstrings or abstracted into new functions with their own docstrings. I'd also like to see the optional_parameters docstring update as its own commit.

This is a lot of comment, but hey this is a lot of PR. We're getting there. Let's pull the independent elements of this out of this to be merged this week and I think the more critical API problems are addressable in short order as well.

I didn't review the integration test implementation for the sake of time and because this review has already been so long. I believe the principles conveyed in the review apply there too, especially the one about duplication in payjoin-test-utils and tech debt. I'll revisit on the next request for review.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +            })?;
`skip(1)` smelled to me.

I think something like this is more idiomatic:

```rs
let agg_psbt = self
    .proposals
    .iter()
    .map(|p| {
        let mut psbt = p.v1.psbt.clone();
        psbt.dangerous_clear_signatures();
        psbt
    })
    .reduce(|mut acc, other| {
        acc.merge_unsigned_tx(other)
            .map_err(InternalMultiPartyError::FailedToMergeProposals)
            .expect("merge_unsigned_tx cannot fail when merging valid PSBTs");
        acc
    })
    .expect("checked proposals not empty above");
```

Additionally, if `dangerous_clear_signatures` returned a new Psbt (which is costless, since `p.v1.psbt` is cloned anyway) instead of `mut` then it could be simplified further to `.map(|proposal| proposal.v1.psbt.dangerous_clear_signatures())`.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +    }
Initially, I felt like it might make sense to directly `extract_v2_reqs() -> Vec<(req, ctx)>` instead of returning the proposals which requires cloning, but I do understand that each proposal may need to poll a different number of times.

I do have some pause cloning the `ctx` because it's supposed to be mutated on each request so that each request has a new nonce. Not sure if cloning the session context is going to allow v2::PayjoinProposal to do this or if, upon e.g. pause and resume, the receiver would be reuse key material. 🤔

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +}
I don't think this is used.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +    pub fn new() -> Self { Self { v2_proposals: vec![] } }
I'd rather see a `FinalizedProposal` produced as output of the `PayjoinProposal` state machine somehow. It seems like this construction would allow FinalizedProposals to be created from unrelated `PayjoinProposal`s. 

I don't think this change needs to block the merge of this, but should block a release of it.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/optional_parameters.rs
> +    pub optimistic_merge: bool,
These are unrelated changes that belong in their own commit

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/optional_parameters.rs
> +            optimistic_merge: false,
I believe `optimistic_merge` should be feature gated on `multi-party`, or a multi_party::Params that encapsulates receive::[v1?::]Params

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/v2/mod.rs
> +pub struct SessionContext {
This is internal so `pub(crate)` instead of `pub`.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/receive/v2/mod.rs
> +    pub fn new(v1: v1::PayjoinProposal, context: SessionContext) -> Self { Self { v1, context } }
I don't want to affect the v2 API with a hack. This could be merged as `pub(crate)` if possible or otherwise integrated into the state machine as your TODO suggests.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/send/mod.rs
> +        }
What is the TODO here? This is a general comment. Record what is TO be DOne.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/send/mod.rs
> +    opt_in_to_optimistic_merge: bool,
Would prefer to have a send::multi_party::serialize_url that encapsulates send::serialize_url to abstract these sepecifics away from the general case.

2025-01-28 18:31 UTC, DanGould commented on payjoin/src/send/multi_party/mod.rs
> +    /// TODO(armins) this is pretty much skipping all the validating and checks
tell me what you want TODO

2025-01-30 03:26 UTC, 0xBEEFCAF3 commented on payjoin/src/psbt/merge/mod.rs
> +    pub fn random_txid() -> Txid {
Not for now. These utils are so general that I could see them being useful in the future. Removing pub

2025-01-30 03:36 UTC, 0xBEEFCAF3 commented on payjoin/src/psbt/merge/mod.rs
> +            // TODO(armins) if we recognize the exact same output this is a not neccecarily an error but an indication for an improved tx structure
yeah this was more of a note. Nothing to do here. Switching to a note comment. Thanks

2025-01-30 03:41 UTC, 0xBEEFCAF3 commented on payjoin/src/psbt/merge/mod.rs
> +            // TODO(armins) if we recognize the exact same output this is a not neccecarily an error but an indication for an improved tx structure
Actually I think this was more of a observation I made while I was POC'ing. Just going to remove

2025-01-30 03:51 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +}
Its not but clippy yelled at me. I'll revisit

2025-01-30 16:09 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +}
Are you using a client clippy config with extra rules?

2025-01-31 02:51 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +type OutputAmountAndIndex = (bitcoin::Amount, usize);
This is moved to #521

2025-01-31 02:54 UTC, 0xBEEFCAF3 commented on payjoin-test-utils/src/lib.rs
> +
Agreed!

2025-01-31 02:57 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +}
No default ones. Ussually additional clippy rules are defined in a toml at the root of the repo

2025-01-31 03:06 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/optional_parameters.rs
> +            optimistic_merge: false,
>or a multi_party::Params that encapsulates receive::[v1?::]Params
This would be my ideal solution. As we add new protocols on top of bip77 these params are going to more and more cluttered with no seperation for concerns. I'll move forward with a feature gate in order to keep the scope of this pr down and update with enapsulation in the future

2025-02-01 22:23 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +    vout: usize,
Merged in #521

2025-02-01 22:32 UTC, 0xBEEFCAF3 commented
@DanGould I'm going to break out the psbt merge commits in its own PR. That work can be independently reviewed while I work on the remainding mp sender

2025-02-08 14:28 UTC, 0xBEEFCAF3 commented on payjoin/src/psbt/merge/mod.rs
> +pub(crate) enum MergePsbtError {
Resolving old PSBT related comments. This work was moved to #523

2025-02-08 14:35 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +            })?;
This code ended up getting simplified to 
```rust
let agg_psbt = self
            .proposals
            .iter()
            .map(|p| p.v1.psbt.clone())
            .reduce(merge_unsigned_tx)
            .expect("length of iterator is checked above");
```

2025-02-12 19:51 UTC, 0xBEEFCAF3 commented
Remaining TODO's discussed in person:
* Multiparty sender type state structs should just wrap v2 structs
* Finalize multiparty sender type state should be its own struct which we can transition to from `GetContext.process_response` 
* Missing process response for finalize type state
* duplicate extract_req code for multi party sender. In a seperate commit abstract to common util method

2025-02-17 14:17 UTC, 0xBEEFCAF3 commented on payjoin/src/send/multi_party/mod.rs
> +        let v2 = v2::SenderBuilder::new(self.0 .0.psbt, self.0 .0.uri)
These spaces ("0. 0") are added after auto-formatting :angry:

2025-02-20 01:52 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +                Amount::from_btc(3650.0)?, // 47*50.0 + 52*25.0 (halving occurs every 150 blocks)
This had to change unfortunately due to the int test setup (`create_and_fund_wallets`) code now mining one less block.

2025-02-20 12:32 UTC, spacebear21 commented on payjoin/tests/integration.rs
> +                Amount::from_btc(3650.0)?, // 47*50.0 + 52*25.0 (halving occurs every 150 blocks)
If it mines one less block shouldn't it be 25 less? Since the last block mined was a halved block.

2025-02-20 13:00 UTC, spacebear21 commented on payjoin/tests/integration.rs
> +                Amount::from_btc(3650.0)?, // 47*50.0 + 52*25.0 (halving occurs every 150 blocks)
yup - https://github.com/bitcoin/bitcoin/blob/e606c577cb257d0927ca6ea939aab06cf0639aad/src/kernel/chainparams.cpp#L533

2025-02-20 16:45 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +                Amount::from_btc(3650.0)?, // 47*50.0 + 52*25.0 (halving occurs every 150 blocks)
This explains why I run out of block subsidy on regtest sometimes. 
I looked over the code diff and my comment is incorrect. The amount is 50 BTC less b/c `create_and_fund_wallets` first mines 101 + len(num_wallets). Technically 100 + len(num_wallet) works but I generated an extra block to cover fees between wallet fundings. In this case num wallets is 2 for reciever and sender. 
And then another block to mine all the transfers to the wallets. **So its 50 BTC less b/c the halving occurs sooner than this test expected.**

In total `create_and_fund_wallet` creates 101 + 2 (num wallets) + 1 (mine the block that funds the wallets) = 104. And at this point the reciver should have 50 BTC. 

In the test we create = 199 blocks. 150-104 = 46 of the blocks generated to the reciever get 50 BTC rewards. 52 blocks get a 25 BTC rewards. 
So...
3700 =  (46 * 50) + (52 * 25) + 50 (the existing balance after `create_and_fund_wallet`)

Thanks for pointing this out

2025-02-21 15:59 UTC, DanGould reviewed
Made it a long way. It seems like most of the TODO items have been addressed

> Remaining TODO's discussed in person:
> *  Multiparty sender type state structs should just wrap v2 structs [dan's edit: they probably don't need to carry `ohttp_relay` fields]

Done

> *  Finalize multiparty sender type state should be its own struct which we can transition to from `GetContext.process_response` 

Not done. This didn't get its own struct, it combined two with `process_response_and_finalize` which produces 2 categories of errors. "and" in a function name is usually a smell.

> * Missing process response for finalize type state

Done

> * duplicate extract_req code for multi party sender. In a seperate commit abstract to common util method

This wasn't done in a separate commit

> * Use the closure pattern for proposal finalization as in other [`finalize_proposal`](https://docs.rs/payjoin/latest/payjoin/receive/struct.ProvisionalProposal.html#method.finalize_proposal) methods

Kind of done but also merged with other functionality

That said this was pretty tricky to review since the commit message doesn't explain *what* changed or *why* it changed [as described in this article](https://cbea.ms/git-commit/#why-not-how)

Putting design decisions (what) and rationale (why) in the commit message is best practice since it allows a reviewer (present for merge or future for debug or understanding) to anticipate the scope of the changes and reason about their impact.

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +    pub fn try_add(
`try_` prefix is for when you have an infallible option in contrast. This should just be called `add`

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +    ) -> Result<&mut Self, MultiPartyError> {
Builder pattern returns the self, not a reference.

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +    pub fn try_build(&self) -> Result<UncheckedProposal, MultiPartyError> {
`try_`, again, is for fallable functions. This is `build()`.

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/receive/multi_party/mod.rs
> +            .expect("length of iterator is checked above");
Still better to return proper error than panic, this could go stale.

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/receive/optional_parameters.rs
> +    // Opt in to optimistic psbt merge
this should be a /// docstring

2025-02-21 15:59 UTC, DanGould commented on payjoin/Cargo.toml
> +multi-party = ["v2", "psbt-merge"]
This feature should replace `psbt-merge`, not add a new one, since `psbt-merge` is useless otherwise.

As discussed in https://github.com/payjoin/rust-payjoin/pull/523#discussion_r1940434050

I also want it to be named `multiparty` (and have the mod named `multiparty`) for brevity and consistency.

2025-02-21 15:59 UTC, DanGould commented on payjoin/src/send/mod.rs
> +    }
Looks like this test and the function it tests should be in payjoin/src/send/multiparty mod

2025-02-22 15:03 UTC, 0xBEEFCAF3 commented on payjoin/src/send/multi_party/mod.rs
> +        let v2 = v2::SenderBuilder::new(self.0 .0.psbt, self.0 .0.uri)
An Alias would work. I would say lets wait till a payjoin cli integration to see what is most ergonomic. Anything at this point for a experimental feature is a pre-optimization.

I've always thought the most ergonomic option is actually to start with a v2::Sender / SenderBuilder. If the feature flag is on you can `build_with_optimistic_merge`. You can think of this as an upgrade. Or you always start with the multiparty sender and downgrade to v2. The former makes more sense to me.

2025-02-22 15:08 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +            .expect("length of iterator is checked above");
Good call out. I can re-use the `NotEnoughProposals` variant here

2025-02-22 17:35 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +    pub fn try_add(
done

2025-02-22 17:35 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +    ) -> Result<&mut Self, MultiPartyError> {
done

2025-02-22 17:35 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multi_party/mod.rs
> +    pub fn try_build(&self) -> Result<UncheckedProposal, MultiPartyError> {
done

2025-02-22 17:35 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/optional_parameters.rs
> +    // Opt in to optimistic psbt merge
done

2025-02-22 17:36 UTC, 0xBEEFCAF3 commented on payjoin/Cargo.toml
> +multi-party = ["v2", "psbt-merge"]
done

2025-02-22 17:36 UTC, 0xBEEFCAF3 commented on payjoin/src/send/mod.rs
> +    }
done and done

2025-02-22 21:11 UTC, DanGould commented
A few comments from my last review were left undone

> this was pretty tricky to review since the commit message doesn't explain what changed or why it changed [as described in this article](https://cbea.ms/git-commit/#why-not-how)
>
> Putting design decisions (what) and rationale (why) in the commit message is best practice since it allows a reviewer (present for merge or future for debug or understanding) to anticipate the scope of the changes and reason about their impact.

Leaving the remaining work in the commit seems like tangent to this main explanation of rationale for and mechanism design for the changes made which ought to be documented in the commit message body.

The other thing is the rename

Module / error names are still multi_party and MultiParty vs multiparty and Multiparty

2025-02-22 21:13 UTC, DanGould commented on payjoin/src/send/multi_party/mod.rs
> +                psbt: Psbt::from_str(ORIGINAL_PSBT).unwrap(),
We are trying to [Remove `.unwrap()` even in tests](https://github.com/payjoin/rust-payjoin/issues/487) but this can be a follow up

2025-02-22 22:21 UTC, 0xBEEFCAF3 commented on payjoin/src/send/multi_party/mod.rs
> +                psbt: Psbt::from_str(ORIGINAL_PSBT).unwrap(),
Oh yeah. Let me just make that change here

2025-02-22 22:27 UTC, 0xBEEFCAF3 commented on payjoin/src/send/multi_party/mod.rs
> +                psbt: Psbt::from_str(ORIGINAL_PSBT).unwrap(),
Done

2025-02-22 23:12 UTC, 0xBEEFCAF3 commented
> It seems like all of these changes got crammed into one commit, which makes it difficult to see that the change is only for deduplication. In the future I'd prefer to see duplicate code introduced in a first commit, and a second commit de-duplicate explicitly.

The diff is not easy to review, I agree. And some small cosmetic changes we're made that could have been left in the first commit. The majority of the changes are removing common code that was introduced in the first commit and removing unused error variants in the `multiparty::error`. But there is also code that is unique to each type of sender which is why this diff has become cumbersome.

2025-03-01 01:07 UTC, DanGould approved these changes
Ok the sender/receiver module separation is beautiful, the v1/v2 apis are unchanged (YTB), and the rationale in the commit messages is tasty.

The one thing that I don't love is that the tests ended up in the `integration::v2` module, and they feature gate them to require `_multiparty`. I'll approve since this is technically sound, but I'd really like to see that one final change made before this goes in so that we can maintain a clear v2 history in the test module and separate the compilation requirements to be strict on the minimum feature set required to use specific behavior.

2025-03-01 01:07 UTC, DanGould commented on payjoin/tests/integration.rs
> +                }
An `integration::[v2?::]multiparty` mod would give this a more beautiful home.

2025-03-01 01:07 UTC, DanGould commented on payjoin/tests/integration.rs
> +            Ok(psbt)
unnecessary assignment

2025-03-01 01:07 UTC, DanGould commented on payjoin/tests/integration.rs
> +                Amount::from_btc(3650.0)?, // 50 (starting reciever blance) + 46*50.0 + 52*25.0 (halving occurs every 150 blocks)
If you gotta document it I think it's better off written explicitly `Amount::from_btc(50 + 46*50.0 + 52*25.0)` and getting real fancy would be with constants `REWARD_H1 = 50`, `REWARD_H2 = 25`. Code semantics are harder to go stale than comments.

2025-03-01 16:40 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multiparty/mod.rs
> +    sender_contexts: Vec<SessionContext>,
I prefer verbosity and overly descriptive names. Esp in a codebase where you have different parties where session has different meanings. I'll change to `contexts`

2025-03-01 16:43 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multiparty/mod.rs
> +    sender_contexts: Vec<SessionContext>,
Done

2025-03-01 16:43 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +            Ok(psbt)
Done

2025-03-01 16:44 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +                }
moved to `integration::multiparty`

2025-03-01 16:44 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +            async fn test_ns1r(services: &TestServices) -> Result<(), BoxError> {
Done

2025-03-01 16:45 UTC, 0xBEEFCAF3 commented on payjoin/tests/integration.rs
> +    ))]
Commit history has been changed to move the ns1r test to `integration::integration`

2025-03-01 16:45 UTC, 0xBEEFCAF3 commented on payjoin/src/send/multiparty/error.rs
> +            InternalFinalizedError::FinalizePsbt(_e) => None,
Done

2025-03-01 16:48 UTC, 0xBEEFCAF3 commented on payjoin/src/receive/multiparty/mod.rs
> +const SUPPORTED_VERSIONS: &[usize] = &[2];
The intention was to disallow pjv1 proposals from being merged. Yes, ideally we just fallback and perform a v2 pj.

2025-03-01 16:50 UTC, 0xBEEFCAF3 commented
Hmm @DanGould I'm getting all green locally running `./contrib/test_local.sh`. Is the int. test being flaky? Can we re-run it?

2025-03-03 15:58 UTC, DanGould commented on payjoin/tests/integration.rs
> +    #[cfg(all(feature = "io", feature = "v2", feature = "_danger-local-https",))]
stray

2025-03-03 18:21 UTC, DanGould approved these changes
IT WAS A JOURNEY BUT WE MADE IT. MULTIPARTY PAYJOIN POC IS GOING TO GET MERGED. YEEREEEEEEE HAWWW 🤠

We both learned a lot about how the other works and the review process in this repository. So much good from this PR. Thank you Armin.

2025-03-03 18:23 UTC, merged

2025-03-03 18:51 UTC, 0xBEEFCAF3 commented
> IT WAS A JOURNEY BUT WE MADE IT. MULTIPARTY PAYJOIN POC IS GOING TO GET MERGED. YEEREEEEEEE HAWWW 🤠
> 
> We both learned a lot about how the other works and the review process in this repository. So much good from this PR. Thank you Armin.

Letss gooo! Thanks for sticking with me through the review process.