Updated payjoin-cli/README.md
payjoin/rust-payjoin pull request #79
Opened 2023-06-03 22:59 UTC by willowenss

Created payjoin-cli README with usage instructions based on my experience

2023-06-03 23:08 UTC, DanGould requested changes
Hell yes! Thanks will

A few points of review

Format using [Github Flavored markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) so that it renders when browsing the repository. Each line here is prefixed with `>` so Github thinks it's all a blockquote I guess.

Config files should be fenced with 

```
```toml
```
blocks and commands with

```
```console
```

blocks

Should be good then.

2023-06-03 23:08 UTC, DanGould commented on payjoin-cli/README.md
> +> s://localhost:3010
8888 != 10000 sats in the request

2023-06-03 23:08 UTC, DanGould commented on payjoin-cli/README.md
> +> Download and install local-ssl-proxy:\
It'd be nice to have a link to local-ssl-proxy and the reason it is necessary

2023-06-04 16:26 UTC, DanGould commented on payjoin-cli/README.md
> + Open a new terminal window and navigate to the  the "sender" directory within payjoin-cli.
There is no sender directory in payjoin-cli unless you make one

2023-06-05 13:03 UTC, DanGould approved these changes

2023-06-05 15:59 UTC, merged

2023-06-07 23:11 UTC, notmandatory commented
@willowenss remind me to show you how to "squash" commits or use `git commit --amend` so as not to clutter up your PRs commit history. 🙂

2023-06-08 14:34 UTC, DanGould commented
> "squash" commits or use git commit --amend so as not to clutter up your PRs commit history. 🙂

When I started getting serious about contributing to rust-bitcoin tcharding introduced me to [this worthwhile read](https://cbea.ms/git-commit/). Mature projects get more anal about commit history for good reason.