add header to response in cli
payjoin/rust-payjoin pull request #88
Opened 2023-07-21 06:48 UTC by jbesraa

resolves #84

2023-07-22 18:09 UTC, DanGould commented
I think you can leave  `.with_additional_header("Access-Control-Allow-Origin", "*")` in one line on [app.rs:164](https://github.com/payjoin/rust-payjoin/pull/88/files#diff-8e6acd92d1374811117a8f9f08387d1a66bd8a3d2ae69c669dd65bab00e441e5R164) instead of on each response

2023-07-23 00:43 UTC, DanGould commented on payjoin-cli/src/app.rs
> +fn serialize_psbt(psbt: &Psbt) -> String {
in general I'd like to see formatting in a separate commit to semantic changes.

This crate is formatted with nightly, `cargo +nightly fmt`, which this PR appears to fail.

2023-07-23 00:44 UTC, DanGould requested changes
Awesome to have this contribution. I left 2 concerns. Thank you!

2023-07-24 06:27 UTC, jbesraa commented
@DanGould moved to the sever initialization. thanks for pointing this out. 
I added the header to local-http as well although iam not sure its strictly needed(?). but could be better for consistency and testing?

2023-07-24 21:27 UTC, DanGould commented
Since this is added in both spots after `handle_web_request` I think this can be fixed by changing that function with one line.

2023-07-26 16:36 UTC, DanGould approved these changes

2023-07-26 16:38 UTC, merged